# Generated by Django 3.1.1 on 2020-10-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_until',
        ),
    ]
