# Generated by Django 3.1.1 on 2020-10-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
