# Generated by Django 3.1.1 on 2020-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_stripecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
