# Generated by Django 3.1.1 on 2020-09-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merch'},
        ),
    ]
