# Generated by Django 3.1.1 on 2020-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20200921_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
