# Generated by Django 3.1.1 on 2020-10-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_merch_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
