# Generated by Django 3.1.1 on 2020-10-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': 'Pricing'},
        ),
    ]
