# Generated by Django 3.1.1 on 2020-10-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20201015_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(default='free-trial', max_length=50),
            preserve_default=False,
        ),
    ]
