# Generated by Django 3.1.1 on 2020-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='featured_artist',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
