# Generated by Django 3.1.1 on 2020-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False),
        ),
    ]
