# Generated by Django 3.1.1 on 2020-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20200921_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclass',
            old_name='masterclass_title',
            new_name='masterclass',
        ),
        migrations.RenameField(
            model_name='masterclassoverview',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
