# Generated by Django 3.1.1 on 2020-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200921_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='lesson_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
