# Generated by Django 3.1.1 on 2020-09-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200921_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterclass',
            options={'verbose_name_plural': 'Masterclass Lessons'},
        ),
        migrations.AlterModelOptions(
            name='masterclassoverview',
            options={'verbose_name_plural': 'Masterclasses'},
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='masterclass_title_friendly_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_friendly_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='masterclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.masterclassoverview'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterclassoverview',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.artist'),
            preserve_default=False,
        ),
    ]
