# Generated by Django 3.1.1 on 2020-10-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20200922_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_description9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_number9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title10',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title5',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title6',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title7',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title8',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='lesson_title9',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url1',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url10',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url3',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url4',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url5',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url6',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url7',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url8',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='video_url9',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='Masterclass',
        ),
    ]
