# Generated by Django 3.1.1 on 2020-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20201013_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url1',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url10',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url3',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url4',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url5',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url6',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url7',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url8',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='masterclassoverview',
            name='img_url9',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
