# Generated by Django 3.1.1 on 2020-10-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20201015_1851'),
        ('lessons', '0007_auto_20201013_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclassoverview',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='subscriptions.Pricing'),
        ),
    ]
